apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter
  labels:
    app: starter
spec:
  selector:
    matchLabels:
      app: starter
  replicas: {{ .Values.starter.replicas }}
  template:
    metadata:
      labels:
        app: starter
        app.kubernetes.io/component: zeebe-client
    spec:
      containers:
        - name: starter
          image: "{{ .Values.global.image.repository }}/starter:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                {{- if $.Values.saas.enabled }}
                -Dapp.tls=true
                {{- else }}
                -Dapp.brokerUrl={{ $.Release.Name }}-core:26500
                {{- end }}
                -Dapp.starter.rate={{ .Values.starter.rate }}
                -Dapp.starter.durationLimit=0
                -Dzeebe.client.requestTimeout=62000
                {{- if .Values.starter.processId }}
                -Dapp.starter.processId={{ .Values.starter.processId | quote }}
                {{- end }}
                {{- if .Values.starter.bpmnXmlPath }}
                -Dapp.starter.bpmnXmlPath={{ .Values.starter.bpmnXmlPath | quote }}
                {{- end }}
                {{- range $index, $value := .Values.starter.extraResources }}
                -Dapp.starter.extraBpmnModels.{{ $index }}={{ $value | quote }}
                {{- end }}
                {{- if .Values.starter.businessKey }}
                -Dapp.starter.businessKey={{ .Values.starter.businessKey | quote }}
                {{- end }}
                {{- if .Values.starter.payloadPath }}
                -Dapp.starter.payloadPath={{ .Values.starter.payloadPath | quote }}
                {{- end }}
                -XX:+HeapDumpOnOutOfMemoryError
            {{- if .Values.starter.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.starter.logLevel | quote }}
            {{- end }}
            {{- if $.Values.saas.enabled }}
            - name: ZEEBE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "zeebe-benchmark.credentials-name" $ }}
                  key: zeebeAddress
            - name: ZEEBE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "zeebe-benchmark.credentials-name" $ }}
                  key: clientId
            - name: ZEEBE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "zeebe-benchmark.credentials-name" $ }}
                  key: clientSecret
            - name: ZEEBE_AUTHORIZATION_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "zeebe-benchmark.credentials-name" $ }}
                  key: authServer
            {{- end }}
          envFrom:
            - configMapRef:
                name: starter-config
                optional: true
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 9600
              name: "http"