---
# Source: zeebe-benchmark/templates/publisher.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  selector:
    matchLabels:
      app: publisher
  replicas: 0
  template:
    metadata:
      labels:
        app: publisher
        app.kubernetes.io/component: zeebe-client
    spec:
      containers:
        - name: publisher
          image: "gcr.io/zeebe-io/starter:ck-main-exporter-8611f3dc"
          imagePullPolicy: Always
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl=zeebe-benchmark-test-zeebe-gateway:26500
                -Dapp.starter.rate=25
                -Dzeebe.client.requestTimeout=62000
                -XX:+HeapDumpOnOutOfMemoryError
                -Dapp.starter.bpmnXmlPath=bpmn/msg_one_task.bpmn
                -Dapp.starter.startViaMessage=true
            - name: LOG_LEVEL
              value: "warn"
          envFrom:
            - configMapRef:
                name: publisher-config
                optional: true
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 9600
              name: "http"
